export const ALLBRIDGE_MCP_CLIENT_HEADER_NAME = 'X-Allbridge-Client';
export const ALLBRIDGE_MCP_CLIENT_HEADER_VALUE = 'allbridge-mcp';

export const ALLBRIDGE_MCP_CLIENT_HEADERS = {
  [ALLBRIDGE_MCP_CLIENT_HEADER_NAME]: ALLBRIDGE_MCP_CLIENT_HEADER_VALUE,
};
